#!/usr/bin/env python3
import os
from multipylib import node, runner, manager

# If --host or --port are not specified, these are used instead
MULTIPY_HOST = os.getenv('MULTIPY_HOST', '127.0.0.1')
MULTIPY_PORT = os.getenv('MULTIPY_PORT', '3000')
MULTIPY_AUTH = os.getenv('MULTIPY_AUTHKEY', 'theclusterkey')

if __name__ == '__main__':
    import argparse

    parser = argparse.ArgumentParser(description='Process tasks in cluster')
    parser.add_argument('--host', dest='host', help='Manager address')
    parser.add_argument('--port', dest='port', help='Manager port')
    parser.add_argument('--key', dest='authkey', help='Manager auth key')
    parser.set_defaults(
        host=MULTIPY_HOST, port=MULTIPY_PORT, authkey=MULTIPY_AUTH)

    # Allowing subcommands
    subparsers = parser.add_subparsers(
        title='Subcommands',
        description='Mode of execution of multipy',
        help='are valid subcommands')

    # node parser (dispatchs start() on multipy/node.py file)
    parser_node = subparsers.add_parser('node')
    parser_node.add_argument(
        '--procs',
        type=int,
        nargs='?',
        default=1,  # How to default to the number of cores in system?
        dest='procs',
        help='Number of processes to spawn in the node')
    parser_node.set_defaults(func=node.start)

    # manager parser (dispatchs start() on multipy/manager.py file)
    parser_manager = subparsers.add_parser('manager')
    parser_manager.set_defaults(func=manager.start)

    # runner parser (dispatchs start() on multipy/runner.py file)
    parser_run = subparsers.add_parser('run')
    parser_run.add_argument(
        'file',
        nargs='+',
        type=argparse.FileType('r'),
        help='Python file with main() to execute')
    parser_run.set_defaults(func=runner.start)

    # dispatch subcommands
    args = parser.parse_args()
    args.func(args)
